--[[

    This file holds maps of IDs for signs that reside at travel target locations.
    They are to be "seen" by the player in order to enable traveling to the
    location; some locations don't have signposts at their target area so other
    activators are used instead.

]]

return {
    -- grep Activator::active_sign_ Morrowind.d/Morrowind.yaml | grep -v _c_ | sort | uniq | awk -F:: '{ print $2 }' | sed "s|\":\$||g"
    morrowindSigns = {
        ["active_sign_khuul_01"] = true,
        ["active_sign_molag_mar_01"] = true,
        ["active_sign_mt_a_01"] = true,
        ["active_sign_mt_kand_01"] = true,
        ["active_sign_tel_vos_01"] = true,
        ["active_sign_vos_01"] = true,
        ["active_sign_ald-ruhnB_01"] = true,
        ["active_sign_ald-ruhnM_01"] = true,
        ["active_sign_ald-ruhn_01"] = true,
        ["active_sign_ald-ruhn_02"] = true,
        ["active_sign_aldvelothi_01"] = true,
        ["active_sign_balmora_01"] = true,
        ["active_sign_balmora_02"] = true,
        ["active_sign_buckmothB_01"] = true,
        ["active_sign_buckmothM_01"] = true,
        ["active_sign_buckmoth_01"] = true,
        ["active_sign_buckmoth_02"] = true,
        ["active_sign_cal_mine_02"] = true,
        ["active_sign_caldera_01"] = true,
        ["active_sign_caldera_02"] = true,
        ["active_sign_dagon_fel_01"] = true,
        ["active_sign_dagon_fell_01"] = true,
        ["active_sign_ebonheart_01"] = true,
        ["active_sign_ebonheart_02"] = true,
        ["active_sign_ghostgate_01"] = true,
        ["active_sign_gnaar _mok_01"] = true,
        ["active_sign_gnaar_mok_02"] = true,
        ["active_sign_gnisis_01"] = true,
        ["active_sign_guartrail_01"] = true,
        ["active_sign_hla_oad_01"] = true,
        ["active_sign_hla_oad_02"] = true,
        ["active_sign_maar_ganB_02"] = true,
        ["active_sign_maar_ganM_02"] = true,
        ["active_sign_maar_gan_01"] = true,
        ["active_sign_maar_gan_02"] = true,
        ["active_sign_moonmoth_01"] = true,
        ["active_sign_pelagiadB_01"] = true,
        ["active_sign_pelagiadM_01"] = true,
        ["active_sign_pelagiad_01"] = true,
        ["active_sign_pelagiad_02"] = true,
        ["active_sign_seydaneen_01"] = true,
        ["active_sign_seydaneen_02"] = true,
        ["active_sign_suran_01"] = true,
        ["active_sign_vivec_01"] = true,
        ["active_sign_vivec_02"] = true,

        -- Extra activators to help "find" locations
        ["ac_shrine_assarnibibi"] = true,
        ["ex_gg_gateswitch_01"] = true,
        ["ex_suran_roadmarker_01"] = true,

        -- Added by us since Mount Kand has no activators to speak of
        ["momw_sft_find_mount_kand"] = true
    },
    -- for o in (grep -i t_com_setmw_sign TR_Mainland.d/TR_Mainland.yaml | tr '[:upper:]' '[:lower:]' | awk '{ print $2 }' | sort | uniq); echo "[\"$o\"] = true,"; end
    trSigns = {
        ["t_com_setmw_signakamora_01"] = true,
        ["t_com_setmw_signakamorab_01"] = true,
        ["t_com_setmw_signakamorae_01"] = true,
        ["t_com_setmw_signakamoram_01"] = true,
        ["t_com_setmw_signakamoran_01"] = true,
        ["t_com_setmw_signwayadurinoua_01"] = true,
        ["t_com_setmw_signwayaegondopo_01"] = true,
        ["t_com_setmw_signwayaimrah_01"] = true,
        ["t_com_setmw_signwayalmalexia_01"] = true,
        ["t_com_setmw_signwayalmalexia_02"] = true,
        ["t_com_setmw_signwayalmasthrr_01"] = true,
        ["t_com_setmw_signwayalmasthrr_02"] = true,
        ["t_com_setmw_signwayaltbosara_01"] = true,
        ["t_com_setmw_signwayaltbosara_02"] = true,
        ["t_com_setmw_signwayammar_01"] = true,
        ["t_com_setmw_signwayandothren_01"] = true,
        ["t_com_setmw_signwayandrethis_01"] = true,
        ["t_com_setmw_signwayarvud_01"] = true,
        ["t_com_setmw_signwayashamul_01"] = true,
        ["t_com_setmw_signwaybaloyra_01"] = true,
        ["t_com_setmw_signwaybodrem_01"] = true,
        ["t_com_setmw_signwayboelighth_01"] = true,
        ["t_com_setmw_signwaybosmora_01"] = true,
        ["t_com_setmw_signwaydarvon_01"] = true,
        ["t_com_setmw_signwaydhorak_01"] = true,
        ["t_com_setmw_signwaydondril_01"] = true,
        ["t_com_setmw_signwaydondril_02"] = true,
        ["t_com_setmw_signwaydreynim_01"] = true,
        ["t_com_setmw_signwaydreynimsp_01"] = true,
        ["t_com_setmw_signwaydunakafel_01"] = true,
        ["t_com_setmw_signwayenamorday_01"] = true,
        ["t_com_setmw_signwayfelmsi_01"] = true,
        ["t_com_setmw_signwayfirewat_01"] = true,
        ["t_com_setmw_signwayfirewata_01"] = true,
        ["t_com_setmw_signwayfortancyl_01"] = true,
        ["t_com_setmw_signwayfortumber_01"] = true,
        ["t_com_setmw_signwayfortwindm_01"] = true,
        ["t_com_setmw_signwaygolmok_01"] = true,
        ["t_com_setmw_signwaygorneb_01"] = true,
        ["t_com_setmw_signwayhelnim_01"] = true,
        ["t_com_setmw_signwayhlabulor_02"] = true,
        ["t_com_setmw_signwayhlanoek_01"] = true,
        ["t_com_setmw_signwayhlersis_01"] = true,
        ["t_com_setmw_signwayidathren_01"] = true,
        ["t_com_setmw_signwayidvano_01"] = true,
        ["t_com_setmw_signwayindrn_01"] = true,
        ["t_com_setmw_signwaykemelze_01"] = true,
        ["t_com_setmw_signwayknockerspass"] = true,
        ["t_com_setmw_signwaykogotel_01"] = true,
        ["t_com_setmw_signwaykragenmar_01"] = true,
        ["t_com_setmw_signwayllothanis_01"] = true,
        ["t_com_setmw_signwayllothanis_02"] = true,
        ["t_com_setmw_signwaymarketstr_01"] = true,
        ["t_com_setmw_signwaymarog_01"] = true,
        ["t_com_setmw_signwaymenaan_01"] = true,
        ["t_com_setmw_signwaymeralag_01"] = true,
        ["t_com_setmw_signwaynarsis_01"] = true,
        ["t_com_setmw_signwaynavand_01"] = true,
        ["t_com_setmw_signwaynecrom_01"] = true,
        ["t_com_setmw_signwaynecrom_02"] = true,
        ["t_com_setmw_signwayoldebonh_01"] = true,
        ["t_com_setmw_signwayoldebonh_02"] = true,
        ["t_com_setmw_signwayomaynis_01"] = true,
        ["t_com_setmw_signwayoranpl_01"] = true,
        ["t_com_setmw_signwayothmura_01"] = true,
        ["t_com_setmw_signwayothrensis_01"] = true,
        ["t_com_setmw_signwayquarryo_01"] = true,
        ["t_com_setmw_signwayquarryp_01"] = true,
        ["t_com_setmw_signwayranyonru_01"] = true,
        ["t_com_setmw_signwayranyonru_02"] = true,
        ["t_com_setmw_signwayranyonrue_01"] = true,
        ["t_com_setmw_signwayrilsoan_01"] = true,
        ["t_com_setmw_signwayroadyr_01"] = true,
        ["t_com_setmw_signwaysailen_01"] = true,
        ["t_com_setmw_signwaysarvanni_01"] = true,
        ["t_com_setmw_signwayseitur_01"] = true,
        ["t_com_setmw_signwayserynthul_01"] = true,
        ["t_com_setmw_signwaytahvel_01"] = true,
        ["t_com_setmw_signwaytear_01"] = true,
        ["t_com_setmw_signwaytelmothri_01"] = true,
        ["t_com_setmw_signwaytelmothri_02"] = true,
        ["t_com_setmw_signwaytelmuthad_01"] = true,
        ["t_com_setmw_signwaytelouada_01"] = true,
        ["t_com_setmw_signwaytelouadaa_01"] = true,
        ["t_com_setmw_signwayteyn_01"] = true,
        ["t_com_setmw_signwaythalothe_01"] = true,
        ["t_com_setmw_signwaytheinnbet_01"] = true,
        ["t_com_setmw_signwaytomarilma_01"] = true,
        ["t_com_setmw_signwayudhlerin_01"] = true,
        ["t_com_setmw_signwayverarchen_01"] = true,
        ["t_com_setmw_signwayvhul_01"] = true,
        ["t_com_setmw_signwayvhul_02"] = true
    }
}
